In [18]:
import numpy as np

In [19]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
#create 1D array 
np.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a=np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
b=np.append(a,[5,6,7,8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [12]:
b.reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [14]:
c=np.array(np.arange(24)).reshape(2,3,4) *10+3
np.append(a,c,axis=0)
np.append(a,c,axis=0).shape
np.append(a,c,axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [15]:
my_hay_stack=np.hstack((a,c))
my_hay_stack
my_hay_stack[0,0,2]=999

In [16]:
#Concatenate
#%%
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
b
togeather=np.concatenate((a,b),axis=0)
togeather.shape
togeather[1,1]=555
togeather


array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [17]:
## Cpmprehensions 
squares=[]
for i in range(10):
    squares.append(i**2)
    
# doing same thing as above using comprehension 
    
squaresN= [i**2 for i in range(10)]

squares3= [i**2 for i in range(30) if i % 3 == 0]
squares3_dict= {i: i**2 for i  in range(30) if i % 3== 0}



In [23]:
#Create a 3×3 numpy array of all True’s
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
#Replace all odd numbers in arr with -1
#similar thing can be done for ODD number
arr= np.arange(10)
arr[arr%2 ==1 ]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
#Replace all odd numbers in arr with -1 without changing arr
arr= np.arange(10)
out=np.where(arr % 2 == 1, -1, arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#np.concatenate([a, b], axis=0)
#np.vstack([a, b])

In [50]:
#How to stack two arrays horizontally?
np.concatenate([a, b], axis=1)
#OR
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [51]:
#Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [52]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [55]:
#Get all items between 5 and 10 from a.
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]


array([ 5,  6,  7,  8,  9, 10])